/** 困难语法句库：成分须覆盖全文（除标点），供「圈出所有语法」使用 */

export type HardGrammarRole =
  | 'subject'
  | 'predicate'
  | 'object'
  | 'attributive'
  | 'adverbial'
  | 'complement'

type HardPart = { text: string; role: HardGrammarRole }

type HardSentence = {
  id: string
  sentence: string
  difficulty: 'hard'
  parts: HardPart[]
}

function S(id: string, sentence: string, parts: HardPart[]): HardSentence {
  return { id, difficulty: 'hard', sentence, parts }
}

/** 复杂：超长单句，多层定状补与把被兼语交织；后半句必须标全 */
export const HARD: HardSentence[] = [
  S('h01', '被风雨打湿的旧衣服还挂在阳台上晾着，细心的妈妈昨晚才把它们一一收回了柜子里。', [
    { text: '被风雨打湿的', role: 'attributive' },
    { text: '旧衣服', role: 'subject' },
    { text: '还', role: 'adverbial' },
    { text: '挂', role: 'predicate' },
    { text: '在阳台上', role: 'complement' },
    { text: '晾着', role: 'complement' },
    { text: '细心的', role: 'attributive' },
    { text: '妈妈', role: 'subject' },
    { text: '昨晚', role: 'adverbial' },
    { text: '才', role: 'adverbial' },
    { text: '把它们', role: 'adverbial' },
    { text: '一一', role: 'adverbial' },
    { text: '收回', role: 'predicate' },
    { text: '了柜子里', role: 'complement' },
  ]),
  S('h02', '那位戴眼镜的年轻老师把这道难题讲解得十分清楚，同学们听完后都恍然大悟地点了点头。', [
    { text: '那位戴眼镜的', role: 'attributive' },
    { text: '年轻老师', role: 'subject' },
    { text: '把这道难题', role: 'adverbial' },
    { text: '讲解', role: 'predicate' },
    { text: '得十分清楚', role: 'complement' },
    { text: '同学们', role: 'subject' },
    { text: '听完后', role: 'adverbial' },
    { text: '都', role: 'adverbial' },
    { text: '恍然大悟地', role: 'adverbial' },
    { text: '点', role: 'predicate' },
    { text: '了点头', role: 'complement' },
  ]),
  S('h03', '经过反复练习，他终于把这首难唱的歌唱得非常动听，台下顿时响起了经久不息的掌声。', [
    { text: '经过反复练习', role: 'adverbial' },
    { text: '他', role: 'subject' },
    { text: '终于', role: 'adverbial' },
    { text: '把这首难唱的歌', role: 'adverbial' },
    { text: '唱', role: 'predicate' },
    { text: '得非常动听', role: 'complement' },
    { text: '台下', role: 'adverbial' },
    { text: '顿时', role: 'adverbial' },
    { text: '响', role: 'predicate' },
    { text: '起了', role: 'complement' },
    { text: '经久不息的', role: 'attributive' },
    { text: '掌声', role: 'object' },
  ]),
  S('h04', '在图书馆安静的角落里，她把那本厚厚的词典几乎查了个遍，窗外的蝉鸣却一刻也不肯停歇。', [
    { text: '在图书馆安静的角落里', role: 'adverbial' },
    { text: '她', role: 'subject' },
    { text: '把那本厚厚的词典', role: 'adverbial' },
    { text: '几乎', role: 'adverbial' },
    { text: '查', role: 'predicate' },
    { text: '了个遍', role: 'complement' },
    { text: '窗外的', role: 'attributive' },
    { text: '蝉鸣', role: 'subject' },
    { text: '却', role: 'adverbial' },
    { text: '一刻也', role: 'adverbial' },
    { text: '不', role: 'adverbial' },
    { text: '肯', role: 'adverbial' },
    { text: '停歇', role: 'predicate' },
  ]),
  S('h05', '被夕阳染红的云彩把整片天空装点得绚丽多彩，归巢的鸟群在天边缓缓画下一道道弧线。', [
    { text: '被夕阳染红的', role: 'attributive' },
    { text: '云彩', role: 'subject' },
    { text: '把整片天空', role: 'adverbial' },
    { text: '装点', role: 'predicate' },
    { text: '得绚丽多彩', role: 'complement' },
    { text: '归巢的', role: 'attributive' },
    { text: '鸟群', role: 'subject' },
    { text: '在天边', role: 'adverbial' },
    { text: '缓缓', role: 'adverbial' },
    { text: '画', role: 'predicate' },
    { text: '下', role: 'complement' },
    { text: '一道道', role: 'attributive' },
    { text: '弧线', role: 'object' },
  ]),
  S('h06', '妈妈昨天在灯火通明的厨房里做了一桌丰盛的家常菜，全家人围坐在桌边吃得津津有味。', [
    { text: '妈妈', role: 'subject' },
    { text: '昨天', role: 'adverbial' },
    { text: '在灯火通明的厨房里', role: 'adverbial' },
    { text: '做', role: 'predicate' },
    { text: '了', role: 'complement' },
    { text: '一桌丰盛的家常菜', role: 'object' },
    { text: '全家人', role: 'subject' },
    { text: '围坐', role: 'predicate' },
    { text: '在桌边', role: 'complement' },
    { text: '吃', role: 'predicate' },
    { text: '得津津有味', role: 'complement' },
  ]),
  S('h07', '他把被雨水淋湿的书包小心翼翼地挂到通风处晾晒，生怕里面的课本再受一点点潮。', [
    { text: '他', role: 'subject' },
    { text: '把被雨水淋湿的书包', role: 'adverbial' },
    { text: '小心翼翼地', role: 'adverbial' },
    { text: '挂', role: 'predicate' },
    { text: '到通风处', role: 'complement' },
    { text: '晾晒', role: 'complement' },
    { text: '生怕', role: 'adverbial' },
    { text: '里面的', role: 'attributive' },
    { text: '课本', role: 'subject' },
    { text: '再', role: 'adverbial' },
    { text: '受', role: 'predicate' },
    { text: '一点点', role: 'attributive' },
    { text: '潮', role: 'object' },
  ]),
  S('h08', '那位从外地赶来的专家把实验数据核对得一丝不苟，连最细微的误差也不肯轻易放过。', [
    { text: '那位从外地赶来的', role: 'attributive' },
    { text: '专家', role: 'subject' },
    { text: '把实验数据', role: 'adverbial' },
    { text: '核对', role: 'predicate' },
    { text: '得一丝不苟', role: 'complement' },
    { text: '连最细微的误差也', role: 'adverbial' },
    { text: '不', role: 'adverbial' },
    { text: '肯', role: 'adverbial' },
    { text: '轻易', role: 'adverbial' },
    { text: '放过', role: 'predicate' },
  ]),
  S('h09', '在暴雨倾盆的夜晚，救援队员仍旧把被困村民一个个转移到了安全的高地。', [
    { text: '在暴雨倾盆的夜晚', role: 'adverbial' },
    { text: '救援队员', role: 'subject' },
    { text: '仍旧', role: 'adverbial' },
    { text: '把被困村民', role: 'adverbial' },
    { text: '一个个', role: 'adverbial' },
    { text: '转移', role: 'predicate' },
    { text: '到了安全的高地', role: 'complement' },
  ]),
  S('h10', '小明把老师布置的那道复杂应用题演算得清清楚楚，步骤工整得让人忍不住点头称赞。', [
    { text: '小明', role: 'subject' },
    { text: '把老师布置的那道复杂应用题', role: 'adverbial' },
    { text: '演算', role: 'predicate' },
    { text: '得清清楚楚', role: 'complement' },
    { text: '步骤', role: 'subject' },
    { text: '工整', role: 'predicate' },
    { text: '得让人忍不住点头称赞', role: 'complement' },
  ]),
  S('h11', '被霜打蔫的菜苗经园丁细心浇灌后又重新挺起了腰杆，绿得让人眼前一亮。', [
    { text: '被霜打蔫的', role: 'attributive' },
    { text: '菜苗', role: 'subject' },
    { text: '经园丁细心浇灌后', role: 'adverbial' },
    { text: '又', role: 'adverbial' },
    { text: '重新', role: 'adverbial' },
    { text: '挺', role: 'predicate' },
    { text: '起了', role: 'complement' },
    { text: '腰杆', role: 'object' },
    { text: '绿', role: 'predicate' },
    { text: '得让人眼前一亮', role: 'complement' },
  ]),
  S('h12', '他请那位经验丰富的师傅把坏掉的机器修得跟新的一样，车间里顿时又响起了轰鸣。', [
    { text: '他', role: 'subject' },
    { text: '请', role: 'predicate' },
    { text: '那位经验丰富的师傅', role: 'object' },
    { text: '把坏掉的机器', role: 'adverbial' },
    { text: '修', role: 'predicate' },
    { text: '得跟新的一样', role: 'complement' },
    { text: '车间里', role: 'adverbial' },
    { text: '顿时', role: 'adverbial' },
    { text: '又', role: 'adverbial' },
    { text: '响', role: 'predicate' },
    { text: '起了', role: 'complement' },
    { text: '轰鸣', role: 'object' },
  ]),
  S('h13', '在伸手不见五指的山洞里，探险队员仍把地图摸索着摊开，借着微弱的手电光辨认方向。', [
    { text: '在伸手不见五指的山洞里', role: 'adverbial' },
    { text: '探险队员', role: 'subject' },
    { text: '仍', role: 'adverbial' },
    { text: '把地图', role: 'adverbial' },
    { text: '摸索着', role: 'adverbial' },
    { text: '摊开', role: 'predicate' },
    { text: '借着微弱的手电光', role: 'adverbial' },
    { text: '辨认', role: 'predicate' },
    { text: '方向', role: 'object' },
  ]),
  S('h14', '被同学们推选出来的班长把这次活动安排得井井有条，连最挑剔的老师也连连称赞。', [
    { text: '被同学们推选出来的', role: 'attributive' },
    { text: '班长', role: 'subject' },
    { text: '把这次活动', role: 'adverbial' },
    { text: '安排', role: 'predicate' },
    { text: '得井井有条', role: 'complement' },
    { text: '连最挑剔的老师也', role: 'adverbial' },
    { text: '连连', role: 'adverbial' },
    { text: '称赞', role: 'predicate' },
  ]),
  S('h15', '爷爷把那本泛黄的旧相册翻了又翻，一张张泛黄的照片把往事拉得又近又远。', [
    { text: '爷爷', role: 'subject' },
    { text: '把那本泛黄的旧相册', role: 'adverbial' },
    { text: '翻', role: 'predicate' },
    { text: '了又翻', role: 'complement' },
    { text: '一张张泛黄的', role: 'attributive' },
    { text: '照片', role: 'subject' },
    { text: '把往事', role: 'adverbial' },
    { text: '拉', role: 'predicate' },
    { text: '得又近又远', role: 'complement' },
  ]),
  S('h16', '她让弟弟把客厅里堆得乱七八糟的玩具一件件收进了箱子，地板总算露出了原来的颜色。', [
    { text: '她', role: 'subject' },
    { text: '让', role: 'predicate' },
    { text: '弟弟', role: 'object' },
    { text: '把客厅里堆得乱七八糟的玩具', role: 'adverbial' },
    { text: '一件件', role: 'adverbial' },
    { text: '收', role: 'predicate' },
    { text: '进了', role: 'complement' },
    { text: '箱子', role: 'object' },
    { text: '地板', role: 'subject' },
    { text: '总算', role: 'adverbial' },
    { text: '露', role: 'predicate' },
    { text: '出了', role: 'complement' },
    { text: '原来的', role: 'attributive' },
    { text: '颜色', role: 'object' },
  ]),
  S('h17', '在寒风刺骨的清晨，环卫工人早已把整条街道清扫得干干净净，连一片落叶也不肯留下。', [
    { text: '在寒风刺骨的清晨', role: 'adverbial' },
    { text: '环卫工人', role: 'subject' },
    { text: '早已', role: 'adverbial' },
    { text: '把整条街道', role: 'adverbial' },
    { text: '清扫', role: 'predicate' },
    { text: '得干干净净', role: 'complement' },
    { text: '连一片落叶也', role: 'adverbial' },
    { text: '不', role: 'adverbial' },
    { text: '肯', role: 'adverbial' },
    { text: '留下', role: 'predicate' },
  ]),
  S('h18', '那位沉默寡言的老船长把航线讲得明明白白，年轻水手听得连大气都不敢出。', [
    { text: '那位沉默寡言的', role: 'attributive' },
    { text: '老船长', role: 'subject' },
    { text: '把航线', role: 'adverbial' },
    { text: '讲', role: 'predicate' },
    { text: '得明明白白', role: 'complement' },
    { text: '年轻水手', role: 'subject' },
    { text: '听', role: 'predicate' },
    { text: '得连大气都不敢出', role: 'complement' },
  ]),
  S('h19', '他把刚写完的作文又从头到尾改了三遍，每一个错别字都被他圈得清清楚楚。', [
    { text: '他', role: 'subject' },
    { text: '把刚写完的作文', role: 'adverbial' },
    { text: '又', role: 'adverbial' },
    { text: '从头到尾', role: 'adverbial' },
    { text: '改', role: 'predicate' },
    { text: '了三遍', role: 'complement' },
    { text: '每一个', role: 'attributive' },
    { text: '错别字', role: 'subject' },
    { text: '都', role: 'adverbial' },
    { text: '被他', role: 'adverbial' },
    { text: '圈', role: 'predicate' },
    { text: '得清清楚楚', role: 'complement' },
  ]),
  S('h20', '被大雪封住的山路让送货的司机焦急得直跺脚，电台里却迟迟没有传来开通的消息。', [
    { text: '被大雪封住的', role: 'attributive' },
    { text: '山路', role: 'subject' },
    { text: '让', role: 'predicate' },
    { text: '送货的司机', role: 'object' },
    { text: '焦急', role: 'predicate' },
    { text: '得直跺脚', role: 'complement' },
    { text: '电台里', role: 'adverbial' },
    { text: '却', role: 'adverbial' },
    { text: '迟迟', role: 'adverbial' },
    { text: '没有', role: 'adverbial' },
    { text: '传来', role: 'predicate' },
    { text: '开通的', role: 'attributive' },
    { text: '消息', role: 'object' },
  ]),
  S('h21', '在热闹非凡的庙会上，艺人把糖人吹得栩栩如生，孩子们围得里三层外三层不肯离去。', [
    { text: '在热闹非凡的庙会上', role: 'adverbial' },
    { text: '艺人', role: 'subject' },
    { text: '把糖人', role: 'adverbial' },
    { text: '吹', role: 'predicate' },
    { text: '得栩栩如生', role: 'complement' },
    { text: '孩子们', role: 'subject' },
    { text: '围', role: 'predicate' },
    { text: '得里三层外三层', role: 'complement' },
    { text: '不', role: 'adverbial' },
    { text: '肯', role: 'adverbial' },
    { text: '离去', role: 'predicate' },
  ]),
  S('h22', '老师叫我把黑板上那道容易混淆的题再给同学们讲一遍，务必讲得人人都能听懂。', [
    { text: '老师', role: 'subject' },
    { text: '叫', role: 'predicate' },
    { text: '我', role: 'object' },
    { text: '把黑板上那道容易混淆的题', role: 'adverbial' },
    { text: '再', role: 'adverbial' },
    { text: '给同学们', role: 'adverbial' },
    { text: '讲', role: 'predicate' },
    { text: '一遍', role: 'complement' },
    { text: '务必', role: 'adverbial' },
    { text: '讲得人人都能听懂', role: 'predicate' },
  ]),
  S('h23', '被月光镀成银色的湖面把岸边的柳树映得影影绰绰，晚风一吹，倒影便碎成了千万片银鳞。', [
    { text: '被月光镀成银色的', role: 'attributive' },
    { text: '湖面', role: 'subject' },
    { text: '把岸边的柳树', role: 'adverbial' },
    { text: '映', role: 'predicate' },
    { text: '得影影绰绰', role: 'complement' },
    { text: '晚风一吹', role: 'adverbial' },
    { text: '倒影', role: 'subject' },
    { text: '便', role: 'adverbial' },
    { text: '碎', role: 'predicate' },
    { text: '成了', role: 'complement' },
    { text: '千万片', role: 'attributive' },
    { text: '银鳞', role: 'object' },
  ]),
  S('h24', '他把父亲留下的那把生了锈的锄头打磨得锃亮，又重新装上了坚实的木柄。', [
    { text: '他', role: 'subject' },
    { text: '把父亲留下的那把生了锈的锄头', role: 'adverbial' },
    { text: '打磨', role: 'predicate' },
    { text: '得锃亮', role: 'complement' },
    { text: '又', role: 'adverbial' },
    { text: '重新', role: 'adverbial' },
    { text: '装', role: 'predicate' },
    { text: '上了', role: 'complement' },
    { text: '坚实的', role: 'attributive' },
    { text: '木柄', role: 'object' },
  ]),
  S('h25', '在伸手可及的书架最高一层，她踮着脚尖把那本尘封已久的小说轻轻抽了出来。', [
    { text: '在伸手可及的书架最高一层', role: 'adverbial' },
    { text: '她', role: 'subject' },
    { text: '踮着脚尖', role: 'adverbial' },
    { text: '把那本尘封已久的小说', role: 'adverbial' },
    { text: '轻轻', role: 'adverbial' },
    { text: '抽', role: 'predicate' },
    { text: '了出来', role: 'complement' },
  ]),
  S('h26', '教练把队员们练得精疲力尽，却仍不放过每一个细小的动作失误，要求必须做到位。', [
    { text: '教练', role: 'subject' },
    { text: '把队员们', role: 'adverbial' },
    { text: '练', role: 'predicate' },
    { text: '得精疲力尽', role: 'complement' },
    { text: '却', role: 'adverbial' },
    { text: '仍', role: 'adverbial' },
    { text: '不放过', role: 'predicate' },
    { text: '每一个细小的动作失误', role: 'object' },
    { text: '要求', role: 'predicate' },
    { text: '必须', role: 'adverbial' },
    { text: '做', role: 'predicate' },
    { text: '到位', role: 'complement' },
  ]),
  S('h27', '被烈日晒得发烫的柏油路把鞋底烫得发软，行人只好贴着树荫一步一步往前挪。', [
    { text: '被烈日晒得发烫的', role: 'attributive' },
    { text: '柏油路', role: 'subject' },
    { text: '把鞋底', role: 'adverbial' },
    { text: '烫', role: 'predicate' },
    { text: '得发软', role: 'complement' },
    { text: '行人', role: 'subject' },
    { text: '只好', role: 'adverbial' },
    { text: '贴着树荫', role: 'adverbial' },
    { text: '一步一步', role: 'adverbial' },
    { text: '往前', role: 'adverbial' },
    { text: '挪', role: 'predicate' },
  ]),
  S('h28', '他请邻居帮忙把钢琴从三楼小心翼翼地抬到了一楼，生怕磕碰了任何一个琴键。', [
    { text: '他', role: 'subject' },
    { text: '请', role: 'predicate' },
    { text: '邻居', role: 'object' },
    { text: '帮忙', role: 'adverbial' },
    { text: '把钢琴', role: 'adverbial' },
    { text: '从三楼', role: 'adverbial' },
    { text: '小心翼翼地', role: 'adverbial' },
    { text: '抬', role: 'predicate' },
    { text: '到了一楼', role: 'complement' },
    { text: '生怕', role: 'adverbial' },
    { text: '磕碰', role: 'predicate' },
    { text: '了', role: 'complement' },
    { text: '任何一个', role: 'attributive' },
    { text: '琴键', role: 'object' },
  ]),
  S('h29', '在灯火阑珊的江边，诗人把那首未完成的诗句改了又改，直到晨光把纸页染成淡金色。', [
    { text: '在灯火阑珊的江边', role: 'adverbial' },
    { text: '诗人', role: 'subject' },
    { text: '把那首未完成的诗句', role: 'adverbial' },
    { text: '改', role: 'predicate' },
    { text: '了又改', role: 'complement' },
    { text: '直到晨光把纸页染成淡金色', role: 'adverbial' },
  ]),
  S('h30', '管理员把归还得皱巴巴的图书一本本抚平、分类、上架，忙得连喝口水的工夫都没有。', [
    { text: '管理员', role: 'subject' },
    { text: '把归还得皱巴巴的图书', role: 'adverbial' },
    { text: '一本本', role: 'adverbial' },
    { text: '抚平', role: 'predicate' },
    { text: '分类', role: 'predicate' },
    { text: '上架', role: 'predicate' },
    { text: '忙', role: 'predicate' },
    { text: '得连喝口水的工夫都没有', role: 'complement' },
  ]),
  S('h31', '被雷雨惊醒的孩子紧紧抓住妈妈的衣角，把小脸埋进她怀里哭得上气不接下气。', [
    { text: '被雷雨惊醒的', role: 'attributive' },
    { text: '孩子', role: 'subject' },
    { text: '紧紧', role: 'adverbial' },
    { text: '抓', role: 'predicate' },
    { text: '住', role: 'complement' },
    { text: '妈妈的衣角', role: 'object' },
    { text: '把小脸', role: 'adverbial' },
    { text: '埋', role: 'predicate' },
    { text: '进她怀里', role: 'complement' },
    { text: '哭', role: 'predicate' },
    { text: '得上气不接下气', role: 'complement' },
  ]),
  S('h32', '导演让演员把这段对白再演得更自然一点，情感层次必须递进得让观众感同身受。', [
    { text: '导演', role: 'subject' },
    { text: '让', role: 'predicate' },
    { text: '演员', role: 'object' },
    { text: '把这段对白', role: 'adverbial' },
    { text: '再', role: 'adverbial' },
    { text: '演', role: 'predicate' },
    { text: '得更自然一点', role: 'complement' },
    { text: '情感层次', role: 'subject' },
    { text: '必须', role: 'adverbial' },
    { text: '递进', role: 'predicate' },
    { text: '得让观众感同身受', role: 'complement' },
  ]),
  S('h33', '在人山人海的车站广场上，志愿者把迷路的老人搀扶到问询处，问询处早已被求助者围得水泄不通。', [
    { text: '在人山人海的车站广场上', role: 'adverbial' },
    { text: '志愿者', role: 'subject' },
    { text: '把迷路的老人', role: 'adverbial' },
    { text: '搀扶', role: 'predicate' },
    { text: '到问询处', role: 'complement' },
    { text: '问询处', role: 'subject' },
    { text: '早已', role: 'adverbial' },
    { text: '被求助者', role: 'adverbial' },
    { text: '围', role: 'predicate' },
    { text: '得水泄不通', role: 'complement' },
  ]),
  S('h34', '他把整箱沉甸甸的苹果扛上肩，一步一步挪上了陡峭的山坡，汗水把后背的衣服湿透了。', [
    { text: '他', role: 'subject' },
    { text: '把整箱沉甸甸的苹果', role: 'adverbial' },
    { text: '扛', role: 'predicate' },
    { text: '上肩', role: 'complement' },
    { text: '一步一步', role: 'adverbial' },
    { text: '挪', role: 'predicate' },
    { text: '上了', role: 'complement' },
    { text: '陡峭的', role: 'attributive' },
    { text: '山坡', role: 'object' },
    { text: '汗水', role: 'subject' },
    { text: '把后背的衣服', role: 'adverbial' },
    { text: '湿透', role: 'predicate' },
    { text: '了', role: 'complement' },
  ]),
  S('h35', '被岁月磨得发亮的石阶把行人的脚步声衬托得格外清晰，寺院里静得只剩风穿过松林。', [
    { text: '被岁月磨得发亮的', role: 'attributive' },
    { text: '石阶', role: 'subject' },
    { text: '把行人的脚步声', role: 'adverbial' },
    { text: '衬托', role: 'predicate' },
    { text: '得格外清晰', role: 'complement' },
    { text: '寺院里', role: 'adverbial' },
    { text: '静', role: 'predicate' },
    { text: '得只剩风穿过松林', role: 'complement' },
  ]),
  S('h36', '她把妈妈织的那件红毛衣叠得整整齐齐，又轻轻放进了即将寄出的包裹里。', [
    { text: '她', role: 'subject' },
    { text: '把妈妈织的那件红毛衣', role: 'adverbial' },
    { text: '叠', role: 'predicate' },
    { text: '得整整齐齐', role: 'complement' },
    { text: '又', role: 'adverbial' },
    { text: '轻轻', role: 'adverbial' },
    { text: '放', role: 'predicate' },
    { text: '进了', role: 'complement' },
    { text: '即将寄出的包裹里', role: 'object' },
  ]),
  S('h37', '在雾气弥漫的清晨，渔民把渔网撒得又远又开，希望能捕到足够养活全家的鱼获。', [
    { text: '在雾气弥漫的清晨', role: 'adverbial' },
    { text: '渔民', role: 'subject' },
    { text: '把渔网', role: 'adverbial' },
    { text: '撒', role: 'predicate' },
    { text: '得又远又开', role: 'complement' },
    { text: '希望', role: 'predicate' },
    { text: '能', role: 'adverbial' },
    { text: '捕', role: 'predicate' },
    { text: '到', role: 'complement' },
    { text: '足够养活全家的', role: 'attributive' },
    { text: '鱼获', role: 'object' },
  ]),
  S('h38', '裁判把双方争执不下的判罚解释得条理分明，赛场上紧绷的气氛才渐渐缓和下来。', [
    { text: '裁判', role: 'subject' },
    { text: '把双方争执不下的判罚', role: 'adverbial' },
    { text: '解释', role: 'predicate' },
    { text: '得条理分明', role: 'complement' },
    { text: '赛场上', role: 'attributive' },
    { text: '紧绷的', role: 'attributive' },
    { text: '气氛', role: 'subject' },
    { text: '才', role: 'adverbial' },
    { text: '渐渐', role: 'adverbial' },
    { text: '缓和', role: 'predicate' },
    { text: '下来', role: 'complement' },
  ]),
  S('h39', '被洪水冲塌的小桥让两岸村民急得团团转，工人们连夜把临时便桥架了起来。', [
    { text: '被洪水冲塌的', role: 'attributive' },
    { text: '小桥', role: 'subject' },
    { text: '让', role: 'predicate' },
    { text: '两岸村民', role: 'object' },
    { text: '急', role: 'predicate' },
    { text: '得团团转', role: 'complement' },
    { text: '工人们', role: 'subject' },
    { text: '连夜', role: 'adverbial' },
    { text: '把临时便桥', role: 'adverbial' },
    { text: '架', role: 'predicate' },
    { text: '了起来', role: 'complement' },
  ]),
  S('h40', '他把桌上摊开的图纸一张张卷好塞进筒里，生怕风再把它们吹得满屋乱飞。', [
    { text: '他', role: 'subject' },
    { text: '把桌上摊开的图纸', role: 'adverbial' },
    { text: '一张张', role: 'adverbial' },
    { text: '卷', role: 'predicate' },
    { text: '好', role: 'complement' },
    { text: '塞', role: 'predicate' },
    { text: '进筒里', role: 'complement' },
    { text: '生怕', role: 'adverbial' },
    { text: '风', role: 'subject' },
    { text: '再', role: 'adverbial' },
    { text: '把它们', role: 'adverbial' },
    { text: '吹', role: 'predicate' },
    { text: '得满屋乱飞', role: 'complement' },
  ]),
  S('h41', '在星光稀少的野外营地，向导把帐篷固定得结结实实，又叮嘱大家千万别离开视线范围。', [
    { text: '在星光稀少的野外营地', role: 'adverbial' },
    { text: '向导', role: 'subject' },
    { text: '把帐篷', role: 'adverbial' },
    { text: '固定', role: 'predicate' },
    { text: '得结结实实', role: 'complement' },
    { text: '又', role: 'adverbial' },
    { text: '叮嘱', role: 'predicate' },
    { text: '大家', role: 'object' },
    { text: '千万', role: 'adverbial' },
    { text: '别', role: 'adverbial' },
    { text: '离开', role: 'predicate' },
    { text: '视线范围', role: 'object' },
  ]),
  S('h42', '主编把这篇漏洞百出的稿子改得面目全非，作者读完后竟觉得比原稿更像自己想说的话。', [
    { text: '主编', role: 'subject' },
    { text: '把这篇漏洞百出的稿子', role: 'adverbial' },
    { text: '改', role: 'predicate' },
    { text: '得面目全非', role: 'complement' },
    { text: '作者', role: 'subject' },
    { text: '读完后', role: 'adverbial' },
    { text: '竟', role: 'adverbial' },
    { text: '觉得', role: 'predicate' },
    { text: '比原稿更像自己想说的话', role: 'object' },
  ]),
  S('h43', '被掌声淹没的获奖者把奖杯举过头顶，泪水把她脸上的妆都冲花了，却笑得比谁都灿烂。', [
    { text: '被掌声淹没的', role: 'attributive' },
    { text: '获奖者', role: 'subject' },
    { text: '把奖杯', role: 'adverbial' },
    { text: '举', role: 'predicate' },
    { text: '过头顶', role: 'complement' },
    { text: '泪水', role: 'subject' },
    { text: '把她脸上的妆', role: 'adverbial' },
    { text: '都', role: 'adverbial' },
    { text: '冲花', role: 'predicate' },
    { text: '了', role: 'complement' },
    { text: '却', role: 'adverbial' },
    { text: '笑', role: 'predicate' },
    { text: '得比谁都灿烂', role: 'complement' },
  ]),
  S('h44', '父亲叫儿子把后院那棵快枯死的桃树再救一救，儿子便整天围着它松土、浇水、治虫。', [
    { text: '父亲', role: 'subject' },
    { text: '叫', role: 'predicate' },
    { text: '儿子', role: 'object' },
    { text: '把后院那棵快枯死的桃树', role: 'adverbial' },
    { text: '再', role: 'adverbial' },
    { text: '救', role: 'predicate' },
    { text: '一救', role: 'complement' },
    { text: '儿子', role: 'subject' },
    { text: '便', role: 'adverbial' },
    { text: '整天', role: 'adverbial' },
    { text: '围着它', role: 'adverbial' },
    { text: '松土', role: 'predicate' },
    { text: '浇水', role: 'predicate' },
    { text: '治虫', role: 'predicate' },
  ]),
  S('h45', '在雷声滚滚的午后，管理员匆忙把窗户关得严严实实，又把怕潮的仪器盖上了防尘布。', [
    { text: '在雷声滚滚的午后', role: 'adverbial' },
    { text: '管理员', role: 'subject' },
    { text: '匆忙', role: 'adverbial' },
    { text: '把窗户', role: 'adverbial' },
    { text: '关', role: 'predicate' },
    { text: '得严严实实', role: 'complement' },
    { text: '又', role: 'adverbial' },
    { text: '把怕潮的仪器', role: 'adverbial' },
    { text: '盖', role: 'predicate' },
    { text: '上了', role: 'complement' },
    { text: '防尘布', role: 'object' },
  ]),
  S('h46', '他把刚从地里挖出的土豆冲洗得干干净净，又按大小分成了三堆准备明天拿去集市。', [
    { text: '他', role: 'subject' },
    { text: '把刚从地里挖出的土豆', role: 'adverbial' },
    { text: '冲洗', role: 'predicate' },
    { text: '得干干净净', role: 'complement' },
    { text: '又', role: 'adverbial' },
    { text: '按大小', role: 'adverbial' },
    { text: '分', role: 'predicate' },
    { text: '成了', role: 'complement' },
    { text: '三堆', role: 'object' },
    { text: '准备', role: 'predicate' },
    { text: '明天', role: 'adverbial' },
    { text: '拿', role: 'predicate' },
    { text: '去', role: 'complement' },
    { text: '集市', role: 'object' },
  ]),
  S('h47', '被掌声和鲜花包围的钢琴家把最后一个音符弹得余音绕梁，全场观众起立鼓掌久久不肯坐下。', [
    { text: '被掌声和鲜花包围的', role: 'attributive' },
    { text: '钢琴家', role: 'subject' },
    { text: '把最后一个音符', role: 'adverbial' },
    { text: '弹', role: 'predicate' },
    { text: '得余音绕梁', role: 'complement' },
    { text: '全场', role: 'attributive' },
    { text: '观众', role: 'subject' },
    { text: '起立', role: 'predicate' },
    { text: '鼓掌', role: 'predicate' },
    { text: '久久', role: 'adverbial' },
    { text: '不', role: 'adverbial' },
    { text: '肯', role: 'adverbial' },
    { text: '坐下', role: 'predicate' },
  ]),
  S('h48', '她让助理把会议纪要整理得一目了然，关键决议必须标得醒目，方便领导快速批阅。', [
    { text: '她', role: 'subject' },
    { text: '让', role: 'predicate' },
    { text: '助理', role: 'object' },
    { text: '把会议纪要', role: 'adverbial' },
    { text: '整理', role: 'predicate' },
    { text: '得一目了然', role: 'complement' },
    { text: '关键', role: 'attributive' },
    { text: '决议', role: 'subject' },
    { text: '必须', role: 'adverbial' },
    { text: '标', role: 'predicate' },
    { text: '得醒目', role: 'complement' },
    { text: '方便', role: 'predicate' },
    { text: '领导', role: 'object' },
    { text: '快速', role: 'adverbial' },
    { text: '批阅', role: 'predicate' },
  ]),
  S('h49', '在秋风萧瑟的田野上，收割机把金黄的稻谷收割得干干净净，谷粒在阳光下闪得刺眼。', [
    { text: '在秋风萧瑟的田野上', role: 'adverbial' },
    { text: '收割机', role: 'subject' },
    { text: '把金黄的稻谷', role: 'adverbial' },
    { text: '收割', role: 'predicate' },
    { text: '得干干净净', role: 'complement' },
    { text: '谷粒', role: 'subject' },
    { text: '在阳光下', role: 'adverbial' },
    { text: '闪', role: 'predicate' },
    { text: '得刺眼', role: 'complement' },
  ]),
  S('h50', '他把那封写了又改、改了又写的家书小心折好塞进信封，又在封口处郑重地贴上了一枚邮票。', [
    { text: '他', role: 'subject' },
    { text: '把那封写了又改、改了又写的家书', role: 'adverbial' },
    { text: '小心', role: 'adverbial' },
    { text: '折', role: 'predicate' },
    { text: '好', role: 'complement' },
    { text: '塞', role: 'predicate' },
    { text: '进信封', role: 'complement' },
    { text: '又', role: 'adverbial' },
    { text: '在封口处', role: 'adverbial' },
    { text: '郑重地', role: 'adverbial' },
    { text: '贴', role: 'predicate' },
    { text: '上了', role: 'complement' },
    { text: '一枚', role: 'attributive' },
    { text: '邮票', role: 'object' },
  ]),
]
